### ISSUE TITLE
DesktopGL nuget package is built against .NET Framework

### ISSUE THREAD

**Issue by FaithLV** [discosultan/quake-console#11]
Hi!

I am trying to reference `MonoGame.QuakeConsole.DesktopGL` nuget package from my project, but upon restore is shows a warning:

```
Package 'MonoGame.QuakeConsole.DesktopGL 1.1.3' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework '.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
```

I tried adding quake-console regardless, but on initialization it throw an Exception `This MGFX effect is for an older release of MonoGame and needs to be rebuilt`, which might or might not be releated running on linux, as I read it is untested.

I am really new to `MonoGame` and game development in general, so I might be using this thing wrong.

[Here is the code if necessary.](https://github.com/FaithLV/orsus/blob/feature/quake-console/src/orsus-opengl/OrsusGame.cs#L29)

**Comment by discosultan** [comment]
@FaithLV, thanks for raising the issue. Indeed, after the upgrade to .NET Core, newer NuGet packages have not been published. I will try to do that in near future but it requires some cleanup in the repo. I have a draft PR open here: https://github.com/discosultan/quake-console/pull/12.

Meanwhile, you can clone this repo, build the project and target the new DesktopGL dll directly.

Cheers!

**Comment by discosultan** [comment]
The following packages versioned 2.0.0 targeting .NET Standard / Core have been published to NuGet:

- MonoGame.QuakeConsole.WindowsDX
- MonoGame.QuakeConsole.ManualInterpreter.WindowsDX
- MonoGame.QuakeConsole.PythonInterpreter.WindowsDX
- MonoGame.QuakeConsole.RoslynInterpreter.WindowsDX
- MonoGame.QuakeConsole.DesktopGL
- MonoGame.QuakeConsole.PythonInterpreter.DesktopGL

**Comment by captainkidd5** [comment]
Love the console, any plans on releasing the manual interpreter for DesktopGL?

**Comment by discosultan** [comment]
@captainkidd5 This should be fairly trivial to do. I'll publish it to NuGet in coming days.

**Comment by discosultan** [comment]
@captainkidd5 I've published the package: https://www.nuget.org/packages/MonoGame.QuakeConsole.ManualInterpreter.DesktopGL/2.0.0

I've only done very preliminary testing. If you run into any issues, just let me know.

**Comment by captainkidd5** [comment]
Cheers thank you!
