### ISSUE TITLE
ManualInterpreter Example Incorrect Letter i Capitalization?

### ISSUE THREAD

**Issue by mk4321** [discosultan/quake-console#7]
Am I crazy or does the code on the main github page for setting up a ManualInterpreter have incorrect capitalization?

`var interpreter = new ManualInterpreter();
console.Interpreter = Interpreter;`

vs

`var interpreter = new ManualInterpreter();
console.Interpreter = interpreter;`

**Comment by discosultan** [comment]
Thanks for pointing out this typo! :)

**Comment by mk4321** [comment]
Thank you for making and sharing this code!  I see the typo it's already fixed, so thank you for that as well.
